cmake_minimum_required(VERSION 3.25)
project(Veridia
    VERSION 0.0.1
    LANGUAGES CXX
)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(MSVC)
    add_compile_options(/utf-8)
endif()

set(CONFIGURATIONS_DIR ${CMAKE_SOURCE_DIR}/cmake)
set(BUILD_DIR ${CMAKE_BINARY_DIR}/out)
set(TEMP_DIR ${CMAKE_BINARY_DIR}/generated)

set(PROJECT_CORE ${CMAKE_PROJECT_NAME}_Core)
set(TARGET_CORE_C_API ${PROJECT_CORE}_C)
set(PROJECT_UI ${CMAKE_PROJECT_NAME}_UI)
set(PROJECT_UI_QTWIDGETS ${CMAKE_PROJECT_NAME}_QtWidgets)
set(PROJECT_UI_QML ${CMAKE_PROJECT_NAME}_Qml)
set(PROJECT_UI_WINUI ${CMAKE_PROJECT_NAME}_WinUI)
set(PROJECT_UI_SWIFTUI ${CMAKE_PROJECT_NAME}_SwiftUI)
set(PROJECT_UI_FLUTTER ${CMAKE_PROJECT_NAME}_Flutter)
set(TARGET_MAIN ${CMAKE_PROJECT_NAME})

add_subdirectory(core)
add_subdirectory(ui)