project(${PROJECT_UI} VERSION 0.0.1)

if(WIN32)
    set(DEFAULT_UI "WINUI")
elseif(APPLE)
    set(DEFAULT_UI "SWIFTUI")
elseif(LINUX)
    set(DEFAULT_UI "FLUTTER")
endif()

if(NOT DEFINED VERIDIA_UI)
    set(VERIDIA_UI ${DEFAULT_UI})
endif()

if(${VERIDIA_UI} STREQUAL "WINUI")
    add_subdirectory(winui)
elseif(${VERIDIA_UI} STREQUAL "SWIFTUI")
    add_subdirectory(swiftui)
elseif(${VERIDIA_UI} STREQUAL "FLUTTER")
    add_subdirectory(flutter)
elseif(${VERIDIA_UI} STREQUAL "QTWIDGETS")
    add_subdirectory(qtwidgets)
elseif(${VERIDIA_UI} STREQUAL "QML")
    add_subdirectory(qml)
else()
    message(FATAL_ERROR "${VERIDIA_UI} is not a supported ui method")
endif()
